import pandas as pd
df = pd.read_csv('youtube_video_stats.csv')
print("Total Videos:", len(df))
print("Total Views:", df['Views'].astype(int).sum())
print("Average Views:", df['Views'].astype(int).mean())
print("Max Views:", df['Views'].astype(int).max())
print("Min Views:", df['Views'].astype(int).min())
print("Average Likes:", df['Likes'].astype(float).mean())
print("Average Comments:", df['Comments'].astype(float).mean())
print("\nTop 5 Videos by Views:")
print(df[['Title', 'Views']].sort_values('Views', ascending=False).head())
